Add all files required for user password reset
sebastiancaraballo/target pull request #4
Opened 2018-09-28 15:18 UTC by sebastiancaraballo

Trello board reference:
https://trello.com/c/1FpW0xPg

Description:
Add all files required for user password reset.

2018-09-28 15:25 UTC, nicofh commented on Gemfile
> +  gem 'addressable'
You should specify gem version

2018-09-28 15:40 UTC, mdornel requested changes

2018-09-28 15:40 UTC, mdornel commented on Gemfile
> +  gem 'addressable'
Add gem version

2018-09-28 15:40 UTC, mdornel commented on spec/requests/api/v1/passwords/create_spec.rb
> +      expect(json[:message]).to match(user.email)
Here I think that you are not expecting what the example is describing. Maybe you should expect the full notification or change the description.

2018-09-28 15:40 UTC, mdornel commented on spec/requests/api/v1/passwords/edit_spec.rb
> +    expect(response.header['Location']).to include('token')
Use `include_json` that you previously used.

2018-09-28 15:40 UTC, mdornel commented on Gemfile
> +  gem 'addressable'
By the way, I do not think that we need this gem

2018-09-28 15:40 UTC, mdornel commented on spec/requests/api/v1/passwords/update_spec.rb
> +  let(:headers) do
I think you there is no need of this complete block

2018-09-28 15:53 UTC, mdornel commented on spec/requests/api/v1/passwords/update_spec.rb
> +  let(:headers) do
Sending the auth_header should be enough

2018-09-28 17:27 UTC, mdornel approved these changes

2018-09-28 17:29 UTC, mdornel reviewed
Remember to update the apiary

2018-09-28 17:30 UTC, nicofh approved these changes

2018-10-01 13:01 UTC, mdornel approved these changes

2018-10-01 13:01 UTC, merged