Add delete target (spot) feature
sebastiancaraballo/target pull request #9
Opened 2018-10-09 16:16 UTC by sebastiancaraballo

Trello board reference:
https://trello.com/c/DGmKqgnw

Description:
Add delete target (spot) feature.

2018-10-09 17:04 UTC, mdornel requested changes

2018-10-09 17:04 UTC, mdornel commented on app/controllers/api/v1/sessions_controller.rb
> +      protect_from_forgery with: :null_sessions
Keep this line unchanged. This should be just `protect_from_forgery with: :null_session`

2018-10-09 17:04 UTC, mdornel commented on app/controllers/api/v1/spots_controller.rb
> +        current_user.spots.destroy(params[:id])
Use bang (!) symbol, this way you will throw the exceptions if the destroy method fail for some reason.

`current_user.spots.destroy!(params[:id])`

2018-10-09 17:04 UTC, mdornel commented on apiary.apib
> +### Destroy a spot [DELETE]
Add a sample of the path for this action please

2018-10-10 16:48 UTC, mdornel approved these changes

2018-10-10 17:14 UTC, jpascual1994 approved these changes

2018-10-10 18:47 UTC, merged